version: '3.8'
services:
  jupyterhub:
    build:
      context: ./jupyterhub
      dockerfile: Dockerfile
    container_name: jupyterhub
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jhub-data:/srv/jupyterhub
      - shared:/shared
    environment:
      GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
      OAUTH_CALLBACK_URL: "${OAUTH_CALLBACK_URL}"
      DOCKER_NETWORK_NAME: hubnet

networks:
  default:
    name: hubnet
    driver: bridge

volumes:
  jhub-data:
  shared:
